Global:
  ManageImages: true
  DracutFlags:
    - "--no-early-microcode"
Components:
  Versions: false
  Enabled: true
  syslinux:
    Enabled: false
EFI:
  Versions: false
  Enabled: true
Kernel:
  CommandLine: zfsbootmenu rd.vconsole.font=ter-v32b loglevel=4 nomodeset zbm.import_policy=force zbm.sort_key=creation modprobe.blacklist=intel_ishtp,intel_ishtp_hid,intel_ish_ipc

